import Head from 'next/head';
import HomePage from 'components/Homepage/HomePage';
import HomePersonalTopHeader from 'root/components/common/Header/HomePersonalTopHeader/HomePersonalTopHeader';
import Footer from 'components/common/Footer/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>GM BOOK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <HomePersonalTopHeader />
      <HomePage />
      <Footer />
    </>
  );
}
