import Head from 'next/head';
import HomePersonalTopHeader from 'root/components/common/Header/HomePersonalTopHeader/HomePersonalTopHeader';
import Footer from 'components/common/Footer/Footer';
import DetailPage from 'components/DetailPage/DetailPage'

export default function Home() {
  return (
    <>
      <Head>
        <title>內容測試</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <HomePersonalTopHeader />
      <DetailPage />
      <Footer />
    </>
  );
}
